staging:
  stack: cedar
  app: boxcar-addons-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - pgbackups: auto-week
    - memcache: 5mb
    - logging: basic
    - scheduler: standard
